name: 'Frontend branch unit test'

on:
  push:
    branches:
      - 'frontend'
      - 'frontend/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Run unit tests for Front-end code base
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - 
        name: Setup NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      - 
        name: Install node dependencies
        run: |
          yarn install
          echo 'Installing Node dependencies'

      - 
        name: Run unit tests
        run: |
          cd frontend
          yarn test
          echo 'Frontend unit test finished'