name: 'Github Pages deployment'

on: 
  push:
    branches:
      - 'master'

jobs:
  build-frontend: 
    runs-on: ubuntu-latest
    name: Install and build frontend dependencies
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - 
        name: Install node dependencies
        run: |
          yarn install
          echo 'Installing Node dependencies'
      - 
        name: Build frontend
        run: |
          yarn build:frontend
          echo 'Bunlding frontend'
      -
        name: Deploy to Github Page
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: frontend/dist

